# This file is based on snippets posted on official Jekyll site:
#   http://jekyllrb.com/docs/continuous-integration/travis-ci/
language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer jekyll-sitemap
script: jekyll build && htmlproofer --disable-external ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
